Покрытие приложения тестами
sadigzade/stellar-burgers pull request #8
Opened 2023-05-07 19:03 UTC by sadigzade

2023-05-07 21:04 UTC, andryxxa93 requested changes
Супер! `Jest` тесты и `Cypress` настроены и работают верно. 
Что понравилось:
- Все редьюсеры покрыты тестами. 
- Тщательное E2E тестирование
- Для одной функции `it` используется один `expect` - это хорошая практика.
- Использовали baseUrl для `cypress`

**Необходимо исправить**
- Добавьте ссылку на деплой проекта в Readme.md
- Добавьте команду запуска cypress в package.json

Удачных правок!

2023-05-07 21:10 UTC, sadigzade commented
Ссылку на deploy вроде как указал в README.md

2023-05-08 07:26 UTC, andryxxa93 commented
Ссылки на деплой в Readme.md нет. Возможно вы забыли добавить данный файл в коммит?

2023-05-08 07:29 UTC, sadigzade commented
Вы про README.md, который находится на ветке gh-pages?

2023-05-08 09:46 UTC, andryxxa93 commented
Супер! Работа принята. Удачи вам и успехов!

2023-05-08 09:54 UTC, merged